### ISSUE TITLE
The labels predicted by the model are of the same type

### ISSUE THREAD

**Issue by Freda1103** [doronharitan/human_activity_recognition_LRCN#7]
Hi !
The labels predicted by the model are of the same type. Is it possibly caused by the operating system used? I use Windows.
Look forward to your suggestions!
![image](https://user-images.githubusercontent.com/55039743/192422702-25fb9ce2-d484-4431-85c8-a05f7b6bd846.png)

**Comment by ZH-UCAS** [comment]
How to fix it ,please
